<a href="https://colab.research.google.com/github/mohanvamsitrade/Tensorflow_Developer_Certificate/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We are going to cover some of the most fundamental concepts of tensors

1. Intro to Tensors
2. Getting information from tensors
3. Tensors and Numpy


In [1]:
# Import Tensorflow

import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the number of dimensions of a tensor

scalar.ndim

0

In [7]:
# Create a Vector

vector = tf.constant([10,10])
vector
#print(vector.ndim)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [20]:
# Create a matrix

matrix = tf.constant([[[10,7],[7,10],[11,11]],
[[10,7],[7,10],[11,11]]])
matrix

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10],
        [11, 11]],

       [[10,  7],
        [ 7, 10],
        [11, 11]]], dtype=int32)>

In [21]:
matrix.ndim

3